FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake qt5-default libboost-all-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
